/**
 * Central configuration for the Kiosk/POS application.
 * Single source of truth for store info, theme tokens, and mock data.
 */

const appConfig = {
  // Store information
  store: {
    name: "Kitchen Co.",
    tagline: "Fresh • Fast • Delicious",
    currencyCode: "CAD",
    currencySymbol: "CA$",
    locale: "en-CA",
  },

  // Theme tokens - changing these will update the entire UI
  theme: {
    colors: {
      // Core colors (HSL values without the hsl() wrapper)
      primary: "222.2 47.4% 11.2%",
      primaryForeground: "210 40% 98%",
      background: "0 0% 100%",
      foreground: "222.2 84% 4.9%",
      secondary: "210 40% 96.1%",
      secondaryForeground: "222.2 47.4% 11.2%",
      muted: "210 40% 96.1%",
      mutedForeground: "215.4 16.3% 46.9%",
      accent: "210 40% 96.1%",
      accentForeground: "222.2 47.4% 11.2%",
      border: "214.3 31.8% 91.4%",
      destructive: "0 84.2% 60.2%",
      destructiveForeground: "210 40% 98%",
    },
    typography: {
      fontFamily: {
        base: "system-ui, -apple-system, sans-serif",
        heading: "system-ui, -apple-system, sans-serif",
      },
      fontSize: {
        xs: "0.75rem",
        sm: "0.875rem",
        base: "1rem",
        lg: "1.125rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        "3xl": "1.875rem",
        "4xl": "2.25rem",
        "5xl": "3rem",
      },
    },
    radius: {
      sm: "0.25rem",
      md: "0.5rem",
      lg: "1rem",
      xl: "1.5rem",
      "2xl": "2rem",
      full: "9999px",
    },
    spacing: {
      xs: "0.25rem",
      sm: "0.5rem",
      md: "1rem",
      lg: "1.5rem",
      xl: "2rem",
      "2xl": "3rem",
      "3xl": "4rem",
    },
  },

  // Mock data for all routes
  mockData: {
    // Kiosk-specific data
    kiosk: {
      header: {
        logoLetter: "K",
        languages: [
          { code: "en", label: "EN" },
          { code: "fr", label: "FR" },
          { code: "es", label: "ES" },
        ],
        defaultLanguage: "en",
      },
      hero: {
        title: "Welcome!",
        subtitle: "Order at your own pace. Tap below to get started.",
        ctaButton: "Start Order",
        ctaSubtext: "Takes about 2 minutes",
      },
      orderTypes: {
        prompt: "How would you like your order?",
        options: [
          { id: "dine-in", label: "Dine In", subtitle: "Eat here", icon: "utensils" },
          { id: "takeout", label: "Takeout", subtitle: "To go", icon: "bag" },
        ],
      },
      footer: {
        helpText: "Need help? Ask a team member nearby.",
      },
      cart: {
        itemCount: 3,
        ctaText: "View Cart",
        ctaSubtext: "Review your items before checkout",
        pageTitle: "Your Cart",
        emptyMessage: "Your cart is empty",
        emptySubtext: "Looks like you haven't added anything yet",
        browseButtonText: "Browse Menu",
        checkoutButtonText: "Continue to Payment",
        addMoreText: "Add more items",
        clearCartText: "Clear Cart",
        specialInstructionsPlaceholder: "Add special instructions (allergies, preferences...)",
      },
      cartItems: [
        { id: "cart-1", productId: "prod-1", name: "Classic Burger", price: 8.99, quantity: 2, modifiers: "No onions", image: "/placeholder.svg" },
        { id: "cart-2", productId: "prod-5", name: "Fries", price: 3.99, quantity: 1, modifiers: "Large", image: "/placeholder.svg" },
        { id: "cart-3", productId: "prod-8", name: "Soda", price: 2.49, quantity: 2, modifiers: "Coca-Cola", image: "/placeholder.svg" },
      ],
      cartSummary: {
        subtotalLabel: "Subtotal",
        subtotalValue: "$26.95",
        taxLabel: "Estimated Tax",
        taxValue: "$2.43",
        totalLabel: "Total",
        totalValue: "$29.38",
        disclaimer: "",
      },
      checkout: {
        pageTitle: "Checkout",
        reviewTitle: "Review your order",
        editCartText: "Edit Cart",
        orderTypeTitle: "Order Type",
        orderTypeOptions: [
          { id: "dine-in", label: "Dine In", subtitle: "Eat here", icon: "utensils" },
          { id: "takeout", label: "Takeout", subtitle: "To go", icon: "shoppingBag" },
        ],
        receiptTitle: "Receipt Preference",
        receiptOptions: [
          { id: "print", label: "Print Receipt", icon: "printer" },
          { id: "email", label: "Email Receipt", icon: "mail" },
          { id: "sms", label: "SMS Receipt", icon: "smartphone" },
        ],
        emailPlaceholder: "Enter your email",
        smsPlaceholder: "Enter your phone number",
        summaryTitle: "Order Summary",
        continueButtonText: "Continue to Payment",
        backToCartText: "Back to Cart",
        addMoreText: "Add more items",
        emptyTitle: "Nothing to checkout",
        emptySubtext: "Your cart is empty. Add some items first!",
        browseMenuText: "Browse Menu",
      },
      payment: {
        pageTitle: "Payment",
        methodsTitle: "Choose payment method",
        methods: [
          { id: "card", label: "Card", subtitle: "Tap, insert, or swipe", icon: "creditCard", enabled: true },
          { id: "wallet", label: "Apple Pay / Google Pay", subtitle: "Mobile wallet", icon: "smartphone", enabled: true },
          { id: "gift", label: "Gift Card", subtitle: "Redeem balance", icon: "gift", enabled: true },
        ],
        nextSteps: {
          card: "Next: Tap, insert, or swipe on the reader",
          wallet: "Next: Hold phone near the reader",
          gift: "Next: Enter gift card code",
        },
        securityText: "Secure payment",
        startPaymentText: "Start Payment",
        backToCheckoutText: "Back to Checkout",
      },
      processing: {
        pageTitle: "Processing Payment",
        cancelText: "Cancel",
        statusHeadline: "Ready for payment",
        processingHeadline: "Processing…",
        instructions: {
          card: "Tap, insert, or swipe your card on the reader",
          wallet: "Hold your phone near the reader",
          gift: "Scan or enter your gift card number",
        },
        cardWarning: "Do not remove card until prompted",
        acceptedCards: ["Visa", "Mastercard", "Amex", "Discover"],
        readerLabel: "Card Reader",
        steps: ["Collecting payment", "Processing"],
        useDifferentMethodText: "Use different method",
        needHelpText: "Need help?",
      },
      success: {
        headline: "Order Successful",
        subtext: "Thank you for your order",
        orderNumber: "4821",
        orderNumberLabel: "Order",
        customerName: "Alex",
        orderForLabel: "Order for",
        waitMessage: "Please wait for your number to be called",
        receiptMessage: "Your receipt will be printed",
        stepAsideMessage: "You can step aside while we prepare your order",
        helpMessage: "Need help? Ask a team member",
        returningMessage: "Returning to home shortly…",
        newOrderText: "Start New Order",
      },
      failure: {
        headline: "Payment Didn't Go Through",
        subtext: "No charge was completed. Please try again.",
        reason: "Card was removed too soon",
        orderTotal: "$29.38",
        itemCount: 3,
        orderSavedMessage: "Your order is still saved.",
        tryAgainText: "Try Again",
        changeMethodText: "Choose Another Payment Method",
        getHelpText: "Get Help",
      },
      receipt: {
        pageTitle: "Receipt",
        storeLine: "Kitchen Co. • In-Store Order",
        orderNumber: "4821",
        orderNumberLabel: "Order #",
        customerName: "Alex",
        orderForLabel: "Order for",
        dateTimeText: "Jan 1, 2026 • 12:34 PM",
        paymentStatusText: "Payment complete",
        items: [
          { name: "Classic Burger", qty: 2, priceText: "$17.98", modifiersText: "No onions" },
          { name: "Fries", qty: 1, priceText: "$3.99", modifiersText: "Large" },
          { name: "Soda", qty: 2, priceText: "$4.98", modifiersText: "Coca-Cola" },
        ],
        summary: {
          subtotalLabel: "Subtotal",
          subtotalText: "$26.95",
          taxLabel: "Estimated Tax",
          taxText: "$2.43",
          totalLabel: "Total",
          totalText: "$29.38",
        },
        delivery: {
          type: "print",
          displayText: "Receipt: Printed",
        },
        keepReceiptNote: "Please keep your receipt for your records.",
        newOrderText: "Start New Order",
        doneText: "Done",
      },
      categories: [
        { id: "cat-1", name: "Burgers", icon: "burger" },
        { id: "cat-2", name: "Sides", icon: "fries" },
        { id: "cat-3", name: "Drinks", icon: "cup" },
        { id: "cat-4", name: "Desserts", icon: "ice-cream" },
      ],
      products: [
        { id: "prod-1", name: "Classic Burger", price: 8.99, categoryId: "cat-1", description: "Our signature beef patty with fresh lettuce, tomato, and special sauce.", image: "/placeholder.svg", badges: [] },
        { id: "prod-2", name: "Cheese Burger", price: 9.99, categoryId: "cat-1", description: "Classic burger topped with melted American cheese.", image: "/placeholder.svg", badges: [] },
        { id: "prod-3", name: "Veggie Burger", price: 9.49, categoryId: "cat-1", description: "Plant-based patty with all the fixings.", image: "/placeholder.svg", badges: ["V"] },
        { id: "prod-4", name: "Spicy Chicken", price: 10.49, categoryId: "cat-1", description: "Crispy chicken breast with spicy mayo and jalapeños.", image: "/placeholder.svg", badges: ["Spicy"] },
        { id: "prod-5", name: "Fries", price: 3.99, categoryId: "cat-2", description: "Golden crispy fries with sea salt.", image: "/placeholder.svg", badges: ["V"] },
        { id: "prod-6", name: "Onion Rings", price: 4.49, categoryId: "cat-2", description: "Crispy battered onion rings.", image: "/placeholder.svg", badges: ["V"] },
        { id: "prod-7", name: "Sweet Potato Fries", price: 4.99, categoryId: "cat-2", description: "Crispy sweet potato fries with chipotle dip.", image: "/placeholder.svg", badges: ["V"] },
        { id: "prod-8", name: "Soda", price: 2.49, categoryId: "cat-3", description: "Your choice of fountain drink.", image: "/placeholder.svg", badges: [] },
        { id: "prod-9", name: "Lemonade", price: 3.29, categoryId: "cat-3", description: "Fresh-squeezed lemonade.", image: "/placeholder.svg", badges: ["V"] },
        { id: "prod-10", name: "Milkshake", price: 5.99, categoryId: "cat-3", description: "Thick and creamy shake in vanilla, chocolate, or strawberry.", image: "/placeholder.svg", badges: [] },
        { id: "prod-11", name: "Ice Cream", price: 4.49, categoryId: "cat-4", description: "Two scoops of premium ice cream.", image: "/placeholder.svg", badges: ["V"] },
        { id: "prod-12", name: "Brownie", price: 3.99, categoryId: "cat-4", description: "Warm chocolate brownie.", image: "/placeholder.svg", badges: [] },
      ],
    },

    // Transactions data (standalone route)
    transactions: {
      pageTitle: "Transactions",
      searchPlaceholder: "Search transaction, receipt, customer, method, total, status…",
      filters: {
        statusOptions: ["All", "Completed", "Refunded", "Voided"],
        methodOptions: ["All Methods", "Card", "Cash", "Wallet"],
        dateOptions: ["Today", "Yesterday", "Last 7 Days"],
      },
      tableHeaders: ["Time", "Transaction #", "Receipt #", "Customer", "Method", "Total", "Status", "Device", "Cashier"],
      emptyState: {
        title: "No transactions found",
        subtitle: "Try changing filters",
      },
      clearFiltersText: "Clear filters",
      previewActions: {
        refund: "Refund",
        void: "Void",
        reprint: "Reprint",
      },
      refundModal: {
        title: "Refund this transaction?",
        message: "This will initiate a refund for the selected transaction. This action cannot be undone.",
        cancelButton: "Cancel",
        confirmButton: "Confirm Refund",
      },
      voidModal: {
        title: "Void this transaction?",
        message: "This will void the selected transaction. This action cannot be undone.",
        cancelButton: "Cancel",
        confirmButton: "Confirm Void",
      },
      rows: [
        {
          id: "txn001",
          timeLabel: "12:41 PM",
          transactionNumber: "1042",
          receiptNumber: "R-8831",
          customerName: "Walk-in",
          paymentMethod: "Card",
          paymentSummary: "Card • Visa •• 4242",
          totalLabel: "$29.38",
          status: "Completed",
          device: "POS",
          cashier: "Alex",
          terminal: "POS-1",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Classic Burger", qtyLabel: "2x", priceLabel: "$17.98" },
            { name: "Fries", qtyLabel: "1x", priceLabel: "$3.99" },
            { name: "Soda", qtyLabel: "2x", priceLabel: "$4.98" },
          ],
          totals: { subtotalLabel: "$26.95", taxLabel: "$2.43", totalLabel: "$29.38" },
        },
        {
          id: "txn002",
          timeLabel: "12:18 PM",
          transactionNumber: "1041",
          receiptNumber: "R-8830",
          customerName: "John D.",
          paymentMethod: "Cash",
          paymentSummary: "Cash",
          totalLabel: "$15.47",
          status: "Completed",
          device: "POS",
          cashier: "Maria",
          terminal: "POS-2",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Veggie Burger", qtyLabel: "1x", priceLabel: "$9.49" },
            { name: "Lemonade", qtyLabel: "1x", priceLabel: "$3.29" },
          ],
          totals: { subtotalLabel: "$12.78", taxLabel: "$2.69", totalLabel: "$15.47" },
        },
        {
          id: "txn003",
          timeLabel: "11:52 AM",
          transactionNumber: "1040",
          receiptNumber: "R-8829",
          customerName: "Walk-in",
          paymentMethod: "Wallet",
          paymentSummary: "Apple Pay",
          totalLabel: "$8.99",
          status: "Refunded",
          device: "Kiosk",
          cashier: "—",
          terminal: "Kiosk-1",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Classic Burger", qtyLabel: "1x", priceLabel: "$8.99" },
          ],
          totals: { subtotalLabel: "$8.99", taxLabel: "$0.00", totalLabel: "$8.99" },
        },
        {
          id: "txn004",
          timeLabel: "11:30 AM",
          transactionNumber: "1039",
          receiptNumber: "R-8828",
          customerName: "Sarah M.",
          paymentMethod: "Card",
          paymentSummary: "Card • Mastercard •• 1234",
          totalLabel: "$42.50",
          status: "Completed",
          device: "POS",
          cashier: "Alex",
          terminal: "POS-1",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Spicy Chicken", qtyLabel: "2x", priceLabel: "$20.98" },
            { name: "Onion Rings", qtyLabel: "2x", priceLabel: "$8.98" },
            { name: "Milkshake", qtyLabel: "2x", priceLabel: "$11.98" },
          ],
          totals: { subtotalLabel: "$41.94", taxLabel: "$0.56", totalLabel: "$42.50" },
        },
        {
          id: "txn005",
          timeLabel: "11:05 AM",
          transactionNumber: "1038",
          receiptNumber: "R-8827",
          customerName: "Walk-in",
          paymentMethod: "Card",
          paymentSummary: "Card • Amex •• 0001",
          totalLabel: "$18.47",
          status: "Voided",
          device: "Kiosk",
          cashier: "—",
          terminal: "Kiosk-2",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Cheese Burger", qtyLabel: "1x", priceLabel: "$9.99" },
            { name: "Fries", qtyLabel: "1x", priceLabel: "$3.99" },
            { name: "Soda", qtyLabel: "1x", priceLabel: "$2.49" },
          ],
          totals: { subtotalLabel: "$16.47", taxLabel: "$2.00", totalLabel: "$18.47" },
        },
        {
          id: "txn006",
          timeLabel: "10:45 AM",
          transactionNumber: "1037",
          receiptNumber: "R-8826",
          customerName: "Mike T.",
          paymentMethod: "Cash",
          paymentSummary: "Cash",
          totalLabel: "$22.95",
          status: "Completed",
          device: "POS",
          cashier: "Maria",
          terminal: "POS-2",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Classic Burger", qtyLabel: "2x", priceLabel: "$17.98" },
            { name: "Soda", qtyLabel: "2x", priceLabel: "$4.98" },
          ],
          totals: { subtotalLabel: "$22.96", taxLabel: "$0.00", totalLabel: "$22.95" },
        },
        {
          id: "txn007",
          timeLabel: "10:22 AM",
          transactionNumber: "1036",
          receiptNumber: "R-8825",
          customerName: "Walk-in",
          paymentMethod: "Wallet",
          paymentSummary: "Google Pay",
          totalLabel: "$13.48",
          status: "Completed",
          device: "Kiosk",
          cashier: "—",
          terminal: "Kiosk-1",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Veggie Burger", qtyLabel: "1x", priceLabel: "$9.49" },
            { name: "Fries", qtyLabel: "1x", priceLabel: "$3.99" },
          ],
          totals: { subtotalLabel: "$13.48", taxLabel: "$0.00", totalLabel: "$13.48" },
        },
        {
          id: "txn008",
          timeLabel: "10:01 AM",
          transactionNumber: "1035",
          receiptNumber: "R-8824",
          customerName: "Lisa R.",
          paymentMethod: "Card",
          paymentSummary: "Card • Visa •• 9999",
          totalLabel: "$35.96",
          status: "Completed",
          device: "POS",
          cashier: "Alex",
          terminal: "POS-1",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Spicy Chicken", qtyLabel: "2x", priceLabel: "$20.98" },
            { name: "Sweet Potato Fries", qtyLabel: "2x", priceLabel: "$9.98" },
            { name: "Lemonade", qtyLabel: "2x", priceLabel: "$6.58" },
          ],
          totals: { subtotalLabel: "$37.54", taxLabel: "-$1.58", totalLabel: "$35.96" },
        },
        {
          id: "txn009",
          timeLabel: "9:45 AM",
          transactionNumber: "1034",
          receiptNumber: "R-8823",
          customerName: "Walk-in",
          paymentMethod: "Cash",
          paymentSummary: "Cash",
          totalLabel: "$8.99",
          status: "Completed",
          device: "POS",
          cashier: "Maria",
          terminal: "POS-2",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Classic Burger", qtyLabel: "1x", priceLabel: "$8.99" },
          ],
          totals: { subtotalLabel: "$8.99", taxLabel: "$0.00", totalLabel: "$8.99" },
        },
        {
          id: "txn010",
          timeLabel: "9:30 AM",
          transactionNumber: "1033",
          receiptNumber: "R-8822",
          customerName: "David K.",
          paymentMethod: "Card",
          paymentSummary: "Card • Mastercard •• 5678",
          totalLabel: "$27.45",
          status: "Completed",
          device: "POS",
          cashier: "Alex",
          terminal: "POS-1",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Cheese Burger", qtyLabel: "2x", priceLabel: "$19.98" },
            { name: "Onion Rings", qtyLabel: "1x", priceLabel: "$4.49" },
            { name: "Soda", qtyLabel: "1x", priceLabel: "$2.49" },
          ],
          totals: { subtotalLabel: "$26.96", taxLabel: "$0.49", totalLabel: "$27.45" },
        },
        {
          id: "txn011",
          timeLabel: "9:12 AM",
          transactionNumber: "1032",
          receiptNumber: "R-8821",
          customerName: "Walk-in",
          paymentMethod: "Wallet",
          paymentSummary: "Apple Pay",
          totalLabel: "$5.99",
          status: "Refunded",
          device: "Kiosk",
          cashier: "—",
          terminal: "Kiosk-2",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Milkshake", qtyLabel: "1x", priceLabel: "$5.99" },
          ],
          totals: { subtotalLabel: "$5.99", taxLabel: "$0.00", totalLabel: "$5.99" },
        },
        // Duplicated data for pagination testing
        {
          id: "txn013",
          timeLabel: "8:41 AM",
          transactionNumber: "1030",
          receiptNumber: "R-8819",
          customerName: "Chris P.",
          paymentMethod: "Card",
          paymentSummary: "Card • Visa •• 7777",
          totalLabel: "$31.25",
          status: "Completed",
          device: "POS",
          cashier: "Alex",
          terminal: "POS-1",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Spicy Chicken", qtyLabel: "2x", priceLabel: "$20.98" },
            { name: "Fries", qtyLabel: "2x", priceLabel: "$7.98" },
          ],
          totals: { subtotalLabel: "$28.96", taxLabel: "$2.29", totalLabel: "$31.25" },
        },
        {
          id: "txn014",
          timeLabel: "8:22 AM",
          transactionNumber: "1029",
          receiptNumber: "R-8818",
          customerName: "Walk-in",
          paymentMethod: "Cash",
          paymentSummary: "Cash",
          totalLabel: "$12.48",
          status: "Completed",
          device: "Kiosk",
          cashier: "—",
          terminal: "Kiosk-1",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Classic Burger", qtyLabel: "1x", priceLabel: "$8.99" },
            { name: "Fries", qtyLabel: "1x", priceLabel: "$3.49" },
          ],
          totals: { subtotalLabel: "$12.48", taxLabel: "$0.00", totalLabel: "$12.48" },
        },
        {
          id: "txn015",
          timeLabel: "8:05 AM",
          transactionNumber: "1028",
          receiptNumber: "R-8817",
          customerName: "Nancy L.",
          paymentMethod: "Wallet",
          paymentSummary: "Apple Pay",
          totalLabel: "$24.97",
          status: "Completed",
          device: "POS",
          cashier: "Maria",
          terminal: "POS-2",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Cheese Burger", qtyLabel: "2x", priceLabel: "$19.98" },
            { name: "Soda", qtyLabel: "2x", priceLabel: "$4.98" },
          ],
          totals: { subtotalLabel: "$24.96", taxLabel: "$0.01", totalLabel: "$24.97" },
        },
        {
          id: "txn016",
          timeLabel: "7:48 AM",
          transactionNumber: "1027",
          receiptNumber: "R-8816",
          customerName: "Walk-in",
          paymentMethod: "Card",
          paymentSummary: "Card • Mastercard •• 4444",
          totalLabel: "$16.47",
          status: "Voided",
          device: "POS",
          cashier: "Alex",
          terminal: "POS-1",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Veggie Burger", qtyLabel: "1x", priceLabel: "$9.49" },
            { name: "Onion Rings", qtyLabel: "1x", priceLabel: "$4.49" },
            { name: "Soda", qtyLabel: "1x", priceLabel: "$2.49" },
          ],
          totals: { subtotalLabel: "$16.47", taxLabel: "$0.00", totalLabel: "$16.47" },
        },
        {
          id: "txn017",
          timeLabel: "7:30 AM",
          transactionNumber: "1026",
          receiptNumber: "R-8815",
          customerName: "Tom H.",
          paymentMethod: "Cash",
          paymentSummary: "Cash",
          totalLabel: "$45.90",
          status: "Completed",
          device: "POS",
          cashier: "Maria",
          terminal: "POS-2",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Classic Burger", qtyLabel: "3x", priceLabel: "$26.97" },
            { name: "Fries", qtyLabel: "3x", priceLabel: "$11.97" },
            { name: "Milkshake", qtyLabel: "1x", priceLabel: "$5.99" },
          ],
          totals: { subtotalLabel: "$44.93", taxLabel: "$0.97", totalLabel: "$45.90" },
        },
        {
          id: "txn018",
          timeLabel: "7:15 AM",
          transactionNumber: "1025",
          receiptNumber: "R-8814",
          customerName: "Walk-in",
          paymentMethod: "Wallet",
          paymentSummary: "Google Pay",
          totalLabel: "$9.49",
          status: "Completed",
          device: "Kiosk",
          cashier: "—",
          terminal: "Kiosk-2",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Veggie Burger", qtyLabel: "1x", priceLabel: "$9.49" },
          ],
          totals: { subtotalLabel: "$9.49", taxLabel: "$0.00", totalLabel: "$9.49" },
        },
        {
          id: "txn019",
          timeLabel: "7:02 AM",
          transactionNumber: "1024",
          receiptNumber: "R-8813",
          customerName: "Rachel G.",
          paymentMethod: "Card",
          paymentSummary: "Card • Amex •• 8888",
          totalLabel: "$38.45",
          status: "Completed",
          device: "POS",
          cashier: "Alex",
          terminal: "POS-1",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Spicy Chicken", qtyLabel: "2x", priceLabel: "$20.98" },
            { name: "Sweet Potato Fries", qtyLabel: "2x", priceLabel: "$9.98" },
            { name: "Lemonade", qtyLabel: "2x", priceLabel: "$6.58" },
          ],
          totals: { subtotalLabel: "$37.54", taxLabel: "$0.91", totalLabel: "$38.45" },
        },
        {
          id: "txn020",
          timeLabel: "6:45 AM",
          transactionNumber: "1023",
          receiptNumber: "R-8812",
          customerName: "Walk-in",
          paymentMethod: "Cash",
          paymentSummary: "Cash",
          totalLabel: "$17.98",
          status: "Refunded",
          device: "POS",
          cashier: "Maria",
          terminal: "POS-2",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Classic Burger", qtyLabel: "2x", priceLabel: "$17.98" },
          ],
          totals: { subtotalLabel: "$17.98", taxLabel: "$0.00", totalLabel: "$17.98" },
        },
        {
          id: "txn021",
          timeLabel: "6:30 AM",
          transactionNumber: "1022",
          receiptNumber: "R-8811",
          customerName: "Kevin B.",
          paymentMethod: "Card",
          paymentSummary: "Card • Visa •• 1111",
          totalLabel: "$22.47",
          status: "Completed",
          device: "Kiosk",
          cashier: "—",
          terminal: "Kiosk-1",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Cheese Burger", qtyLabel: "1x", priceLabel: "$9.99" },
            { name: "Fries", qtyLabel: "1x", priceLabel: "$3.99" },
            { name: "Milkshake", qtyLabel: "1x", priceLabel: "$5.99" },
          ],
          totals: { subtotalLabel: "$19.97", taxLabel: "$2.50", totalLabel: "$22.47" },
        },
        {
          id: "txn022",
          timeLabel: "6:15 AM",
          transactionNumber: "1021",
          receiptNumber: "R-8810",
          customerName: "Walk-in",
          paymentMethod: "Wallet",
          paymentSummary: "Apple Pay",
          totalLabel: "$14.48",
          status: "Completed",
          device: "POS",
          cashier: "Alex",
          terminal: "POS-1",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Veggie Burger", qtyLabel: "1x", priceLabel: "$9.49" },
            { name: "Sweet Potato Fries", qtyLabel: "1x", priceLabel: "$4.99" },
          ],
          totals: { subtotalLabel: "$14.48", taxLabel: "$0.00", totalLabel: "$14.48" },
        },
        {
          id: "txn023",
          timeLabel: "6:00 AM",
          transactionNumber: "1020",
          receiptNumber: "R-8809",
          customerName: "Amy S.",
          paymentMethod: "Card",
          paymentSummary: "Card • Mastercard •• 2222",
          totalLabel: "$33.96",
          status: "Completed",
          device: "POS",
          cashier: "Maria",
          terminal: "POS-2",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Spicy Chicken", qtyLabel: "2x", priceLabel: "$20.98" },
            { name: "Onion Rings", qtyLabel: "2x", priceLabel: "$8.98" },
            { name: "Soda", qtyLabel: "2x", priceLabel: "$4.98" },
          ],
          totals: { subtotalLabel: "$34.94", taxLabel: "-$0.98", totalLabel: "$33.96" },
        },
        {
          id: "txn024",
          timeLabel: "5:45 AM",
          transactionNumber: "1019",
          receiptNumber: "R-8808",
          customerName: "Walk-in",
          paymentMethod: "Cash",
          paymentSummary: "Cash",
          totalLabel: "$8.99",
          status: "Completed",
          device: "Kiosk",
          cashier: "—",
          terminal: "Kiosk-2",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Classic Burger", qtyLabel: "1x", priceLabel: "$8.99" },
          ],
          totals: { subtotalLabel: "$8.99", taxLabel: "$0.00", totalLabel: "$8.99" },
        },
        {
          id: "txn025",
          timeLabel: "5:30 AM",
          transactionNumber: "1018",
          receiptNumber: "R-8807",
          customerName: "Brian M.",
          paymentMethod: "Card",
          paymentSummary: "Card • Visa •• 5555",
          totalLabel: "$27.96",
          status: "Voided",
          device: "POS",
          cashier: "Alex",
          terminal: "POS-1",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Cheese Burger", qtyLabel: "2x", priceLabel: "$19.98" },
            { name: "Fries", qtyLabel: "2x", priceLabel: "$7.98" },
          ],
          totals: { subtotalLabel: "$27.96", taxLabel: "$0.00", totalLabel: "$27.96" },
        },
        {
          id: "txn026",
          timeLabel: "5:15 AM",
          transactionNumber: "1017",
          receiptNumber: "R-8806",
          customerName: "Walk-in",
          paymentMethod: "Wallet",
          paymentSummary: "Google Pay",
          totalLabel: "$13.48",
          status: "Completed",
          device: "Kiosk",
          cashier: "—",
          terminal: "Kiosk-1",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Veggie Burger", qtyLabel: "1x", priceLabel: "$9.49" },
            { name: "Fries", qtyLabel: "1x", priceLabel: "$3.99" },
          ],
          totals: { subtotalLabel: "$13.48", taxLabel: "$0.00", totalLabel: "$13.48" },
        },
        {
          id: "txn027",
          timeLabel: "5:00 AM",
          transactionNumber: "1016",
          receiptNumber: "R-8805",
          customerName: "Diana F.",
          paymentMethod: "Cash",
          paymentSummary: "Cash",
          totalLabel: "$41.94",
          status: "Completed",
          device: "POS",
          cashier: "Maria",
          terminal: "POS-2",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Spicy Chicken", qtyLabel: "2x", priceLabel: "$20.98" },
            { name: "Milkshake", qtyLabel: "2x", priceLabel: "$11.98" },
            { name: "Fries", qtyLabel: "2x", priceLabel: "$7.98" },
          ],
          totals: { subtotalLabel: "$40.94", taxLabel: "$1.00", totalLabel: "$41.94" },
        },
        {
          id: "txn028",
          timeLabel: "4:45 AM",
          transactionNumber: "1015",
          receiptNumber: "R-8804",
          customerName: "Walk-in",
          paymentMethod: "Card",
          paymentSummary: "Card • Amex •• 6666",
          totalLabel: "$19.98",
          status: "Completed",
          device: "POS",
          cashier: "Alex",
          terminal: "POS-1",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Cheese Burger", qtyLabel: "2x", priceLabel: "$19.98" },
          ],
          totals: { subtotalLabel: "$19.98", taxLabel: "$0.00", totalLabel: "$19.98" },
        },
        {
          id: "txn029",
          timeLabel: "4:30 AM",
          transactionNumber: "1014",
          receiptNumber: "R-8803",
          customerName: "Steve J.",
          paymentMethod: "Wallet",
          paymentSummary: "Apple Pay",
          totalLabel: "$15.47",
          status: "Refunded",
          device: "Kiosk",
          cashier: "—",
          terminal: "Kiosk-2",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Classic Burger", qtyLabel: "1x", priceLabel: "$8.99" },
            { name: "Lemonade", qtyLabel: "2x", priceLabel: "$6.58" },
          ],
          totals: { subtotalLabel: "$15.57", taxLabel: "-$0.10", totalLabel: "$15.47" },
        },
        {
          id: "txn030",
          timeLabel: "4:15 AM",
          transactionNumber: "1013",
          receiptNumber: "R-8802",
          customerName: "Walk-in",
          paymentMethod: "Cash",
          paymentSummary: "Cash",
          totalLabel: "$26.97",
          status: "Completed",
          device: "POS",
          cashier: "Maria",
          terminal: "POS-2",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Veggie Burger", qtyLabel: "2x", priceLabel: "$18.98" },
            { name: "Sweet Potato Fries", qtyLabel: "1x", priceLabel: "$4.99" },
            { name: "Soda", qtyLabel: "1x", priceLabel: "$2.49" },
          ],
          totals: { subtotalLabel: "$26.46", taxLabel: "$0.51", totalLabel: "$26.97" },
        },
        {
          id: "txn031",
          timeLabel: "4:00 AM",
          transactionNumber: "1012",
          receiptNumber: "R-8801",
          customerName: "Laura C.",
          paymentMethod: "Card",
          paymentSummary: "Card • Visa •• 9090",
          totalLabel: "$52.43",
          status: "Completed",
          device: "POS",
          cashier: "Alex",
          terminal: "POS-1",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Spicy Chicken", qtyLabel: "3x", priceLabel: "$31.47" },
            { name: "Onion Rings", qtyLabel: "3x", priceLabel: "$13.47" },
            { name: "Milkshake", qtyLabel: "1x", priceLabel: "$5.99" },
          ],
          totals: { subtotalLabel: "$50.93", taxLabel: "$1.50", totalLabel: "$52.43" },
        },
        {
          id: "txn032",
          timeLabel: "3:45 AM",
          transactionNumber: "1011",
          receiptNumber: "R-8800",
          customerName: "Walk-in",
          paymentMethod: "Wallet",
          paymentSummary: "Google Pay",
          totalLabel: "$12.98",
          status: "Completed",
          device: "Kiosk",
          cashier: "—",
          terminal: "Kiosk-1",
          dateLabel: "Jan 1, 2026",
          items: [
            { name: "Classic Burger", qtyLabel: "1x", priceLabel: "$8.99" },
            { name: "Fries", qtyLabel: "1x", priceLabel: "$3.99" },
          ],
          totals: { subtotalLabel: "$12.98", taxLabel: "$0.00", totalLabel: "$12.98" },
        },
      ],
      pagination: {
        rowsPerPage: 20,
        prevText: "Prev",
        nextText: "Next",
        pageOfText: "Page {current} of {total}",
      },
    },

    // POS-specific data
    pos: {
      topBar: {
        searchPlaceholder: "Search products…",
        newOrderText: "New Order",
      },
      categories: [
        { id: "all", name: "All Items" },
        { id: "cat-1", name: "Burgers" },
        { id: "cat-2", name: "Sides" },
        { id: "cat-3", name: "Drinks" },
        { id: "cat-4", name: "Desserts" },
      ],
      quickItems: [
        { id: "quick-1", name: "Classic Burger", price: 8.99 },
        { id: "quick-2", name: "Fries", price: 3.99 },
        { id: "quick-3", name: "Soda", price: 2.49 },
        { id: "quick-4", name: "Cheese Burger", price: 9.99 },
      ],
      products: [
        { id: "prod-1", name: "Classic Burger", price: 8.99, categoryId: "cat-1", image: "/placeholder.svg" },
        { id: "prod-2", name: "Cheese Burger", price: 9.99, categoryId: "cat-1", image: "/placeholder.svg" },
        { id: "prod-3", name: "Veggie Burger", price: 9.49, categoryId: "cat-1", image: "/placeholder.svg" },
        { id: "prod-4", name: "Spicy Chicken", price: 10.49, categoryId: "cat-1", image: "/placeholder.svg" },
        { id: "prod-5", name: "Fries", price: 3.99, categoryId: "cat-2", image: "/placeholder.svg" },
        { id: "prod-6", name: "Onion Rings", price: 4.49, categoryId: "cat-2", image: "/placeholder.svg" },
        { id: "prod-7", name: "Sweet Potato Fries", price: 4.99, categoryId: "cat-2", image: "/placeholder.svg" },
        { id: "prod-8", name: "Soda", price: 2.49, categoryId: "cat-3", image: "/placeholder.svg" },
        { id: "prod-9", name: "Lemonade", price: 3.29, categoryId: "cat-3", image: "/placeholder.svg" },
        { id: "prod-10", name: "Milkshake", price: 5.99, categoryId: "cat-3", image: "/placeholder.svg" },
        { id: "prod-11", name: "Ice Cream", price: 4.49, categoryId: "cat-4", image: "/placeholder.svg" },
        { id: "prod-12", name: "Brownie", price: 3.99, categoryId: "cat-4", image: "/placeholder.svg" },
      ],
      cart: {
        title: "Current Sale",
        customerLabel: "Customer: Walk-in",
        holdText: "Hold",
        recallText: "Recall",
        emptyMessage: "No items in cart",
        emptySubtext: "Select products to add",
      },
      cartItems: [
        { id: "cart-1", name: "Classic Burger", price: 8.99, quantity: 2 },
        { id: "cart-2", name: "Fries", price: 3.99, quantity: 1 },
        { id: "cart-3", name: "Soda", price: 2.49, quantity: 2 },
      ],
      summary: {
        subtotalLabel: "Subtotal",
        subtotalValue: "$26.95",
        taxLabel: "Tax",
        taxValue: "$2.43",
        totalLabel: "Total",
        totalValue: "$29.38",
      },
      actions: {
        checkoutText: "Checkout",
        payCashText: "Pay Cash",
        payCardText: "Pay Card",
        discountText: "Discount",
        refundText: "Refund",
        openDrawerText: "Open Drawer",
        printReceiptText: "Print Receipt",
      },
      navigation: [
        { id: "orders", label: "Orders", path: "/pos/orders" },
        { id: "checkout", label: "Checkout", path: "/pos/checkout" },
        { id: "refund", label: "Refund", path: "/pos/refund" },
        { id: "shift", label: "Shift", path: "/pos/shift" },
      ],
      customer: "Walk-in",
      cashPayment: {
        title: "Cash Payment",
        customerLabel: "Customer",
        amountDueLabel: "Amount Due",
        amountDueValue: "$29.38",
        helperText: "Enter cash received",
        cashReceivedLabel: "Cash received",
        cashReceivedDefault: "$0.00",
        changeDueLabel: "Change due",
        changeDuePlaceholder: "—",
        quickBills: [
          { label: "$5", value: "5.00", tone: "bill5" },
          { label: "$10", value: "10.00", tone: "bill10" },
          { label: "$20", value: "20.00", tone: "bill20" },
          { label: "$50", value: "50.00", tone: "bill50" },
          { label: "$100", value: "100.00", tone: "bill100" },
        ],
        exactLabel: "Exact",
        completeButtonText: "Complete Cash Sale",
        cancelButtonText: "Cancel",
        splitCardButtonText: "Pay Rest with Card",
      },
      cardPayment: {
        title: "Card Payment",
        status: "Ready for payment",
        instructions: "Ask the customer to tap, insert, or swipe their card.",
        helperNote: "Do not remove card until prompted.",
        acceptedMethods: ["Visa", "Mastercard", "Amex", "Interac"],
        steps: [
          { id: "select", label: "Select", active: false },
          { id: "pay", label: "Pay", active: true },
          { id: "complete", label: "Complete", active: false },
        ],
        cancelText: "Cancel",
        changeMethodText: "Change payment method",
      },
      processing: {
        pageTitle: "Card Payment",
        statusTitle: "Ready for customer",
        statusTitleProcessing: "Processing…",
        statusSubtitle: "Ask customer to tap, insert, or swipe their card.",
        instructionItems: [
          { id: "tap", label: "Tap", icon: "contactless" },
          { id: "insert", label: "Insert", icon: "chip" },
          { id: "swipe", label: "Swipe", icon: "swipe" },
        ],
        doNotRemoveNote: "Do not remove card until prompted",
        acceptedMethods: ["Visa", "Mastercard", "Amex", "Discover", "Apple Pay"],
        amountDue: "$29.38",
        saleNumber: "Sale #4821",
        troubleshootingTips: [
          "If tap fails, try inserting the chip",
          "If chip fails, try swiping the card",
          "Ask customer to hold card steady on the reader",
          "Try a different card if issues persist",
          "Check for debris on the card reader",
        ],
        helpSteps: [
          "Ensure the card reader is powered on and connected",
          "Ask the customer to try their card again",
          "If issues persist, try a different payment method",
          "Contact support if the problem continues",
        ],
        cancelText: "Cancel",
        needHelpText: "Need help?",
        completeText: "Complete",
        tryAgainText: "Try Again",
        changeMethodText: "Change Payment Method",
      },
      success: {
        pageTitle: "Payment Approved",
        saleNumber: "#4821",
        orderNumber: "1042",
        customerName: "Walk-in",
        timeLabel: "12:34 PM",
        headline: "Payment Successful",
        subtext: "Transaction completed successfully",
        status: "Approved",
        amountPaid: "$29.38",
        paymentSummary: "Card • Visa •• 4242",
        authRef: "Auth: TXN-928471",
        nextActions: {
          primary: "Back to Main Screen",
          printReceipt: "Print Receipt",
        },
        backToSaleText: "Back to Sale",
      },
      failure: {
        pageTitle: "Payment Failed",
        headline: "Card Declined",
        message: "Ask customer to try again or use another payment method.",
        reasonLabel: "Insufficient funds",
        amountDue: "$29.38",
        saleNumber: "#4821",
        timeLabel: "12:34 PM",
        details: [
          { label: "Reference", value: "REF-928471" },
          { label: "Auth Attempt", value: "1 of 3" },
          { label: "Device Message", value: "DO NOT HONOR" },
        ],
        showDetailsText: "Show details",
        hideDetailsText: "Hide details",
        primaryActions: {
          tryAgain: "Try Again",
          changeMethod: "Change Payment Method",
          payCash: "Pay Cash",
        },
        utilityActions: {
          differentCard: "Use Different Card",
          splitTender: "Split Tender",
          cancelSale: "Cancel Sale",
          needHelp: "Need Help?",
        },
        troubleshootingTips: [
          "Try inserting the chip if tap fails",
          "Ask customer to hold card steady on the reader",
          "Try swiping the card as a last resort",
          "Request a different card from the customer",
          "Check the card reader connection",
          "If issues persist, offer to take cash",
        ],
        reassuranceNote: "Items are still in the cart. Nothing has been charged.",
        helpSteps: [
          "Ask the customer to try the same card again",
          "If declined again, request a different card",
          "Offer alternative payment methods (cash, mobile wallet)",
          "Check the card reader is properly connected",
          "If repeated failures, contact support",
        ],
        backToSaleText: "Back to Sale",
      },
      receipt: {
        pageTitle: "Receipts",
        searchPlaceholder: "Search receipt #, customer, last 4…",
        exportText: "Export",
        printLastText: "Print Last",
        dateRangeOptions: [
          { id: "today", label: "Today" },
          { id: "yesterday", label: "Yesterday" },
          { id: "last7", label: "Last 7 Days" },
          { id: "custom", label: "Custom" },
        ],
        statusFilters: [
          { id: "all", label: "All" },
          { id: "completed", label: "Completed" },
          { id: "refunded", label: "Refunded" },
          { id: "voided", label: "Voided" },
        ],
        paymentFilters: [
          { id: "all", label: "All Methods" },
          { id: "card", label: "Card" },
          { id: "cash", label: "Cash" },
          { id: "wallet", label: "Wallet" },
        ],
        tableHeaders: ["Time", "Receipt #", "Customer", "Method", "Total", "Status"],
        emptyState: {
          title: "No receipts found",
          subtitle: "Try clearing your filters",
        },
        previewActions: {
          reprint: "Reprint",
          send: "Send",
          refund: "Refund",
          viewFull: "View Full",
        },
        sendModal: {
          title: "Send Receipt",
          emailLabel: "Email",
          smsLabel: "SMS",
          emailPlaceholder: "customer@email.com",
          smsPlaceholder: "(555) 123-4567",
          emailHelper: "Receipt will be sent to this email address",
          smsHelper: "Receipt will be sent via text message",
          sendButton: "Send Receipt",
          cancelButton: "Cancel",
        },
        refundModal: {
          title: "Refund this receipt?",
          message: "This will initiate a refund for the selected transaction. This action cannot be undone.",
          cancelButton: "Cancel",
          confirmButton: "Confirm Refund",
        },
        receipts: [
          {
            id: "rcpt-001",
            timeLabel: "12:34 PM",
            receiptNumber: "#4821",
            customerLabel: "Walk-in",
            paymentMethodLabel: "Card",
            paymentSummary: "Card • Visa •• 4242",
            totalLabel: "$29.38",
            status: "Completed",
            authRef: "TXN-928471",
            last4: "4242",
            channel: "In-store",
            notes: ["Sent to kitchen", "Printed"],
            items: [
              { name: "Classic Burger", qtyLabel: "2x", priceLabel: "$17.98" },
              { name: "Fries", qtyLabel: "1x", priceLabel: "$3.99" },
              { name: "Soda", qtyLabel: "2x", priceLabel: "$4.98" },
            ],
            totals: {
              subtotalLabel: "$26.95",
              taxLabel: "$2.43",
              totalLabel: "$29.38",
            },
          },
          {
            id: "rcpt-002",
            timeLabel: "12:18 PM",
            receiptNumber: "#4820",
            customerLabel: "John D.",
            paymentMethodLabel: "Cash",
            paymentSummary: "Cash",
            totalLabel: "$15.47",
            status: "Completed",
            authRef: "—",
            last4: "—",
            channel: "In-store",
            notes: ["Printed"],
            items: [
              { name: "Veggie Burger", qtyLabel: "1x", priceLabel: "$9.49" },
              { name: "Lemonade", qtyLabel: "1x", priceLabel: "$3.29" },
            ],
            totals: {
              subtotalLabel: "$12.78",
              taxLabel: "$2.69",
              totalLabel: "$15.47",
            },
          },
          {
            id: "rcpt-003",
            timeLabel: "11:52 AM",
            receiptNumber: "#4819",
            customerLabel: "Walk-in",
            paymentMethodLabel: "Wallet",
            paymentSummary: "Apple Pay",
            totalLabel: "$8.99",
            status: "Refunded",
            authRef: "TXN-928470",
            last4: "—",
            channel: "In-store",
            notes: ["Refunded", "Emailed"],
            items: [
              { name: "Classic Burger", qtyLabel: "1x", priceLabel: "$8.99" },
            ],
            totals: {
              subtotalLabel: "$8.99",
              taxLabel: "$0.00",
              totalLabel: "$8.99",
            },
          },
          {
            id: "rcpt-004",
            timeLabel: "11:30 AM",
            receiptNumber: "#4818",
            customerLabel: "Sarah M.",
            paymentMethodLabel: "Card",
            paymentSummary: "Card • Mastercard •• 1234",
            totalLabel: "$42.50",
            status: "Completed",
            authRef: "TXN-928469",
            last4: "1234",
            channel: "In-store",
            notes: ["Sent to kitchen", "Printed", "Emailed"],
            items: [
              { name: "Spicy Chicken", qtyLabel: "2x", priceLabel: "$20.98" },
              { name: "Onion Rings", qtyLabel: "2x", priceLabel: "$8.98" },
              { name: "Milkshake", qtyLabel: "2x", priceLabel: "$11.98" },
            ],
            totals: {
              subtotalLabel: "$38.64",
              taxLabel: "$3.86",
              totalLabel: "$42.50",
            },
          },
          {
            id: "rcpt-005",
            timeLabel: "10:45 AM",
            receiptNumber: "#4817",
            customerLabel: "Walk-in",
            paymentMethodLabel: "Card",
            paymentSummary: "Card • Amex •• 0001",
            totalLabel: "$12.48",
            status: "Voided",
            authRef: "TXN-928468",
            last4: "0001",
            channel: "In-store",
            notes: ["Voided"],
            items: [
              { name: "Fries", qtyLabel: "2x", priceLabel: "$7.98" },
              { name: "Soda", qtyLabel: "1x", priceLabel: "$2.49" },
            ],
            totals: {
              subtotalLabel: "$10.47",
              taxLabel: "$2.01",
              totalLabel: "$12.48",
            },
          },
        ],
      },
      transactions: {
        pageTitle: "Transactions",
        searchPlaceholder: "Search transaction #, receipt #, customer…",
        exportText: "Export",
        printReportText: "Print Report",
        dateRangeOptions: [
          { id: "today", label: "Today" },
          { id: "yesterday", label: "Yesterday" },
          { id: "last7", label: "Last 7 Days" },
          { id: "custom", label: "Custom" },
        ],
        statusFilters: [
          { id: "all", label: "All" },
          { id: "completed", label: "Completed" },
          { id: "refunded", label: "Refunded" },
          { id: "voided", label: "Voided" },
        ],
        paymentFilters: [
          { id: "all", label: "All Methods" },
          { id: "card", label: "Card" },
          { id: "cash", label: "Cash" },
          { id: "wallet", label: "Wallet" },
        ],
        tableHeaders: ["Time", "Transaction #", "Receipt #", "Customer", "Payment", "Total", "Status"],
        emptyState: {
          title: "No transactions found",
          subtitle: "Adjust filters to see results",
        },
        detailActions: {
          viewReceipt: "View Receipt",
          reprint: "Reprint",
          refund: "Refund",
          void: "Void Transaction",
        },
        refundModal: {
          title: "Refund Transaction?",
          message: "This will initiate a full refund for this transaction. This action cannot be undone.",
          cancelButton: "Cancel",
          confirmButton: "Confirm Refund",
        },
        voidModal: {
          title: "Void Transaction?",
          message: "This will void the transaction and reverse all changes. This action cannot be undone.",
          cancelButton: "Cancel",
          confirmButton: "Void Transaction",
        },
        transactions: [
          {
            id: "txn-001",
            transactionId: "TXN-928471",
            receiptNumber: "#4821",
            timeLabel: "12:34 PM",
            dateLabel: "Jan 1, 2026",
            customerLabel: "Walk-in",
            paymentMethodLabel: "Card",
            paymentSummary: "Card • Visa •• 4242",
            totalLabel: "$29.38",
            status: "Completed",
            meta: {
              cashier: "Alex M.",
              terminal: "POS-01",
              notes: "Standard sale",
            },
            items: [
              { name: "Classic Burger", qtyLabel: "2x", priceLabel: "$17.98" },
              { name: "Fries", qtyLabel: "1x", priceLabel: "$3.99" },
              { name: "Soda", qtyLabel: "2x", priceLabel: "$4.98" },
            ],
            totals: {
              subtotalLabel: "$26.95",
              taxLabel: "$2.43",
              totalLabel: "$29.38",
            },
          },
          {
            id: "txn-002",
            transactionId: "TXN-928470",
            receiptNumber: "#4820",
            timeLabel: "12:18 PM",
            dateLabel: "Jan 1, 2026",
            customerLabel: "John D.",
            paymentMethodLabel: "Cash",
            paymentSummary: "Cash",
            totalLabel: "$15.47",
            status: "Completed",
            meta: {
              cashier: "Alex M.",
              terminal: "POS-01",
              notes: "Cash sale",
            },
            items: [
              { name: "Veggie Burger", qtyLabel: "1x", priceLabel: "$9.49" },
              { name: "Lemonade", qtyLabel: "1x", priceLabel: "$3.29" },
            ],
            totals: {
              subtotalLabel: "$12.78",
              taxLabel: "$2.69",
              totalLabel: "$15.47",
            },
          },
          {
            id: "txn-003",
            transactionId: "TXN-928469",
            receiptNumber: "#4819",
            timeLabel: "11:52 AM",
            dateLabel: "Jan 1, 2026",
            customerLabel: "Walk-in",
            paymentMethodLabel: "Wallet",
            paymentSummary: "Apple Pay",
            totalLabel: "$8.99",
            status: "Refunded",
            meta: {
              cashier: "Sam K.",
              terminal: "POS-02",
              notes: "Customer changed mind",
            },
            items: [
              { name: "Classic Burger", qtyLabel: "1x", priceLabel: "$8.99" },
            ],
            totals: {
              subtotalLabel: "$8.99",
              taxLabel: "$0.00",
              totalLabel: "$8.99",
            },
          },
          {
            id: "txn-004",
            transactionId: "TXN-928468",
            receiptNumber: "#4818",
            timeLabel: "11:30 AM",
            dateLabel: "Jan 1, 2026",
            customerLabel: "Sarah M.",
            paymentMethodLabel: "Card",
            paymentSummary: "Card • Mastercard •• 1234",
            totalLabel: "$42.50",
            status: "Completed",
            meta: {
              cashier: "Alex M.",
              terminal: "POS-01",
              notes: "Large order",
            },
            items: [
              { name: "Spicy Chicken", qtyLabel: "2x", priceLabel: "$20.98" },
              { name: "Onion Rings", qtyLabel: "2x", priceLabel: "$8.98" },
              { name: "Milkshake", qtyLabel: "2x", priceLabel: "$11.98" },
            ],
            totals: {
              subtotalLabel: "$38.64",
              taxLabel: "$3.86",
              totalLabel: "$42.50",
            },
          },
          {
            id: "txn-005",
            transactionId: "TXN-928467",
            receiptNumber: "#4817",
            timeLabel: "10:45 AM",
            dateLabel: "Jan 1, 2026",
            customerLabel: "Walk-in",
            paymentMethodLabel: "Card",
            paymentSummary: "Card • Amex •• 0001",
            totalLabel: "$12.48",
            status: "Voided",
            meta: {
              cashier: "Sam K.",
              terminal: "POS-02",
              notes: "Duplicate entry",
            },
            items: [
              { name: "Fries", qtyLabel: "2x", priceLabel: "$7.98" },
              { name: "Soda", qtyLabel: "1x", priceLabel: "$2.49" },
            ],
            totals: {
              subtotalLabel: "$10.47",
              taxLabel: "$2.01",
              totalLabel: "$12.48",
            },
          },
          {
            id: "txn-006",
            transactionId: "TXN-928466",
            receiptNumber: "#4816",
            timeLabel: "10:15 AM",
            dateLabel: "Jan 1, 2026",
            customerLabel: "Mike R.",
            paymentMethodLabel: "Card",
            paymentSummary: "Card • Visa •• 5678",
            totalLabel: "$18.97",
            status: "Completed",
            meta: {
              cashier: "Alex M.",
              terminal: "POS-01",
              notes: "",
            },
            items: [
              { name: "Cheese Burger", qtyLabel: "1x", priceLabel: "$9.99" },
              { name: "Sweet Potato Fries", qtyLabel: "1x", priceLabel: "$4.99" },
              { name: "Lemonade", qtyLabel: "1x", priceLabel: "$3.29" },
            ],
            totals: {
              subtotalLabel: "$18.27",
              taxLabel: "$0.70",
              totalLabel: "$18.97",
            },
          },
        ],
      },
      settings: {
        pageTitle: "Settings",
        terminalLabel: "POS-01",
        meta: {
          version: "2.4.1",
          build: "2026.01.01",
          environment: "Test Mode",
        },
        tabs: [
          { id: "general", label: "General" },
          { id: "payments", label: "Payments" },
          { id: "receipts", label: "Receipts" },
          { id: "hardware", label: "Hardware" },
          { id: "staff", label: "Staff" },
          { id: "about", label: "About" },
        ],
        general: {
          storeNameLabel: "Store Name",
          timezoneLabel: "Timezone",
          timezoneOptions: [
            { id: "utc", label: "UTC" },
            { id: "est", label: "Eastern (EST)" },
            { id: "cst", label: "Central (CST)" },
            { id: "mst", label: "Mountain (MST)" },
            { id: "pst", label: "Pacific (PST)" },
          ],
          languageLabel: "Language",
          languageOptions: [
            { id: "en", label: "English" },
            { id: "es", label: "Spanish" },
            { id: "fr", label: "French" },
          ],
          dateFormatLabel: "Date Format",
          dateFormatOptions: [
            { id: "mdy", label: "MM/DD/YYYY" },
            { id: "dmy", label: "DD/MM/YYYY" },
            { id: "ymd", label: "YYYY-MM-DD" },
          ],
          resetDefaultsText: "Reset to Defaults",
          resetConfirmTitle: "Reset Settings?",
          resetConfirmMessage: "This will restore all general settings to their default values.",
        },
        payments: {
          sectionTitle: "Payment Methods",
          methods: [
            { id: "card", label: "Card Payments", enabled: true },
            { id: "cash", label: "Cash", enabled: true },
            { id: "wallet", label: "Mobile Wallet", enabled: true },
          ],
          tipsLabel: "Tips Enabled",
          tipsEnabled: true,
          signatureLabel: "Signature Required",
          signatureEnabled: false,
          offlineModeLabel: "Offline Mode",
          offlineModeEnabled: false,
          offlineModeHelper: "Requires additional hardware setup",
        },
        receipts: {
          defaultMethodLabel: "Default Receipt Method",
          methodOptions: [
            { id: "print", label: "Print" },
            { id: "email", label: "Email" },
            { id: "sms", label: "SMS" },
            { id: "none", label: "None" },
          ],
          autoPrintLabel: "Auto-print Receipt",
          autoPrintEnabled: true,
          showOrderNumberLabel: "Show Order Number",
          showOrderNumberEnabled: true,
          footerTextLabel: "Receipt Footer Text",
          footerTextPlaceholder: "Thank you for visiting Kitchen Co.!",
        },
        hardware: {
          sectionTitle: "Connected Devices",
          cardReaderLabel: "Card Reader",
          cardReaderStatus: "Connected",
          printerLabel: "Receipt Printer",
          printerStatus: "Ready",
          cashDrawerLabel: "Cash Drawer",
          cashDrawerEnabled: true,
          testDeviceText: "Test",
          refreshDevicesText: "Refresh Devices",
        },
        staff: {
          activeCashierLabel: "Active Cashier",
          activeCashier: "Alex M.",
          switchCashierText: "Switch Cashier",
          pinRequiredLabel: "PIN Required for Refunds",
          pinRequiredEnabled: true,
          shiftRemindersLabel: "Shift End Reminders",
          shiftRemindersEnabled: true,
        },
        about: {
          appName: "Kitchen Co. POS",
          versionLabel: "Version",
          version: "2.4.1",
          buildLabel: "Build Date",
          build: "January 1, 2026",
          licenseLabel: "License",
          licenseValue: "Commercial",
          supportLabel: "Support",
          supportLink: "support@kitchenco.com",
          termsText: "Terms of Service",
          privacyText: "Privacy Policy",
        },
        footer: {
          saveText: "Save Changes",
          discardText: "Discard",
          helperText: "Changes apply to this terminal",
        },
      },
    },

    // Active Orders data (standalone kitchen display)
    activeOrders: {
      topBar: {
        title: "Active Orders",
        liveLabel: "Live",
        searchPlaceholder: "Search order #, name…",
        refreshLabel: "Refresh",
        filters: [
          { id: "all", label: "All" },
          { id: "new", label: "New" },
          { id: "preparing", label: "Preparing" },
          { id: "ready", label: "Ready" },
          { id: "delayed", label: "Delayed" },
        ],
      },
      columns: [
        { id: "new", label: "New", emptyLabel: "No new orders" },
        { id: "preparing", label: "Preparing", emptyLabel: "Nothing being prepared" },
        { id: "ready", label: "Ready", emptyLabel: "No orders ready" },
      ],
      orders: [
        {
          id: "ao-1",
          orderNumber: "1042",
          customerLabel: "Walk-in",
          type: "Dine-in",
          status: "new",
          placedTimeLabel: "12:41 PM",
          items: [
            { name: "Classic Burger", qtyLabel: "2×", modifiersLabel: "No onions" },
            { name: "Fries", qtyLabel: "1×", modifiersLabel: "Large" },
            { name: "Soda", qtyLabel: "2×", modifiersLabel: "Coca-Cola" },
          ],
          tags: ["Paid"],
          notes: null,
        },
        {
          id: "ao-2",
          orderNumber: "1043",
          customerLabel: "Sarah M.",
          type: "Takeout",
          status: "new",
          placedTimeLabel: "12:45 PM",
          items: [
            { name: "Veggie Burger", qtyLabel: "1×", modifiersLabel: "Extra pickles" },
            { name: "Sweet Potato Fries", qtyLabel: "1×", modifiersLabel: null },
            { name: "Lemonade", qtyLabel: "1×", modifiersLabel: null },
          ],
          tags: ["Rush", "Allergy"],
          notes: "Gluten allergy - use dedicated fryer",
        },
        {
          id: "ao-3",
          orderNumber: "1040",
          customerLabel: "Mike D.",
          type: "Delivery",
          status: "preparing",
          placedTimeLabel: "12:32 PM",
          items: [
            { name: "Spicy Chicken", qtyLabel: "2×", modifiersLabel: "Extra spicy" },
            { name: "Onion Rings", qtyLabel: "1×", modifiersLabel: null },
            { name: "Milkshake", qtyLabel: "2×", modifiersLabel: "Chocolate" },
          ],
          tags: ["Paid"],
          notes: "Ring doorbell twice",
        },
        {
          id: "ao-4",
          orderNumber: "1041",
          customerLabel: "Walk-in",
          type: "Dine-in",
          status: "preparing",
          placedTimeLabel: "12:38 PM",
          items: [
            { name: "Cheese Burger", qtyLabel: "3×", modifiersLabel: null },
            { name: "Fries", qtyLabel: "2×", modifiersLabel: "Regular" },
            { name: "Brownie", qtyLabel: "1×", modifiersLabel: "Warm" },
          ],
          tags: [],
          notes: null,
        },
        {
          id: "ao-5",
          orderNumber: "1038",
          customerLabel: "James L.",
          type: "Takeout",
          status: "ready",
          placedTimeLabel: "12:22 PM",
          items: [
            { name: "Classic Burger", qtyLabel: "1×", modifiersLabel: null },
            { name: "Fries", qtyLabel: "1×", modifiersLabel: "Large" },
            { name: "Ice Cream", qtyLabel: "1×", modifiersLabel: "Vanilla" },
          ],
          tags: ["Paid"],
          notes: null,
        },
        {
          id: "ao-6",
          orderNumber: "1039",
          customerLabel: "Emma W.",
          type: "Dine-in",
          status: "ready",
          placedTimeLabel: "12:28 PM",
          items: [
            { name: "Veggie Burger", qtyLabel: "2×", modifiersLabel: "No sauce" },
            { name: "Sweet Potato Fries", qtyLabel: "2×", modifiersLabel: null },
          ],
          tags: [],
          notes: null,
        },
      ],
      emptyState: {
        title: "No active orders",
        subtitle: "New orders will appear here automatically",
      },
    },
  },
};

export default appConfig;
